apiVersion: v1
kind: Service
metadata:
  labels:
    app: podinfo
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
  name: podinfo-deployment
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 9898
  selector:
    app: podinfo
  type: LoadBalancer
